[package]
name = "yapm_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yapm"
path = "main.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
